image: python:3.9

stages:
  - test

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

lintest-flake:
    stage: test
    script:
        - echo "Starting linters..."
        - pip install flake8
        - flake8 --extend-exclude=venv/

lintest-pylint:
    stage: test
    script:
        - echo "Starting linters..."
        - python -m pip install --upgrade pip && pip install -r requirements.txt
        - pip install pylint
        - pylint src/ --generated-members=numpy.*,torch.*