version: "3"
services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
        - -U
        - admin
    container_name: database
  backend:
    image: semantic_bot:latest
    environment:
      PG_NAME: postgres
      PG_USER: admin
      PG_PASSWORD: admin
      PG_HOST: database
      PG_PORT: 5432
      TOKEN: ...
      GPT_TOKEN: ...
    depends_on:
      database:
        condition: service_healthy
    container_name: backend
volumes:
  postgres:
