name: CI

on: push

jobs: 
  lintest-flake: 
    runs-on: ubuntu-latest 
    container: python:3.9 
    steps: 
      - uses: actions/checkout@v2 
      - name: Set up Python 3.9 
        uses: actions/setup-python@v2 
        with: python-version: 3.9

      - name: Install dependencies 
        run: |  
          python -m pip install --upgrade pip  

          pip install virtualenv

          virtualenv venv

          source venv/bin/activate

      - name: Lint with flake8 
        run : |  
          pip install flake8
          flake8 --extend-exclude=venv/          

       cache :   paths :     - .cache/pip     - venv/  

  lintest-pylint :    runs-on : ubuntu-latest    container : python : 3.9    steps :     - uses : actions / checkout @ v2     - name : Set up Python 3.9      uses : actions / setup - python @ v2      with :       python - version : 3.9     - name : Install dependencies      run : |         python - m pip install -- upgrade pip         pip install - r requirements . txt         pip install pylint     - name : Lint with pylint      run : |         pylint bot / -- generated - members = numpy . * , torch . *         pylint training / -- generated - members = numpy . * , torch . *       cache :     paths :       - .cache / pip       - venv /
